### ISSUE TITLE
stderr is not included in execution logs

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/save-cloud#190]
Here
https://github.com/analysis-dev/save-cloud/blob/cd22fc8da811a012ef010c7c940bcc57d958c1a0/save-agent/src/linuxX64Main/kotlin/org/cqfn/save/agent/SaveAgent.kt#L162-L170
we are using ProcessBuilder to run the command and redirect stdout into the file, stderr is discarded

**Comment by kgevorkyan** [comment]
I think this should be probably closed in https://github.com/analysis-dev/save/pull/220
After it, `stderr` and `stdout` collected into the same file

**Comment by kgevorkyan** [comment]
Tested, `stderr` is included
