### ISSUE TITLE
Orchestrator: Mark agents as crashed after a number of skipped heartbeats

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/save-cloud#208]
After, e.g., 4 skipped heartbeats agent should be marked as crashed and orchestrator should attempt to stop it, in case it's hanging. This task depends on #315 , because now heartbeats can be irregular, since they are waiting on process execution

**Comment by akuleshov7** [comment]
also we need to make checks for the following:
1) If AGENT returned only part of results -> MARK ALL other tests as FAILED (with internal error);
2) If Agent stooped heartbeating for a configurable time ->  MARK ALL tests from this agent as FAILED (with internal error) and stop an agent;
3) Check why SAVE processBuilder does not work with save timeouts;
