### ISSUE TITLE
Frontend: Focus on the test-resources information fields is lost after editing (Git mode page)

### ISSUE THREAD

**Issue by kgevorkyan** [analysis-dev/save-cloud#426]
If we will copy-paste the some info to that fields all will be okay,

but if we will try to edit fields and enter the values **manually** the focus of cursor will be lost, and it will be necessary to click to the fields one more time after each new symbol, which is quite inconvenient 

![bug](https://user-images.githubusercontent.com/26010098/143594531-9d90bf13-abdd-44dd-a15b-d714894d205f.PNG)

**Comment by akuleshov7** [comment]
My bug, will fix it. Very inconvenient right now
