### ISSUE TITLE
Frontend + CI: Add some tests that the page can render

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/save-cloud#537]
https://kotlinlang.org/docs/js-running-tests.html
https://jestjs.io/docs/tutorial-react

Also we should check react warnings in tests (and fix those that are already present): https://www.benmvp.com/blog/catch-warnings-jest-tests/

-------

JS test frameworks support async functions; in K/JS it can be mimicked by test methods returning `Promise` (more info [here](https://youtrack.jetbrains.com/issue/KT-19813)):
```kotlin
@Test
fun test: Promise<Any> {}
```

---

Does Kotlin actually have interop with Jest? There are [references in code](https://github.com/JetBrains/kotlin/blob/v1.6.21/libraries/kotlin.test/js/src/main/kotlin/kotlin/test/adapters/JasmineLikeAdapter.kt), but I couldn't figure out how to setup this with gradle

---

REST API: Mock Service Worker (MSW). Also possible to generate stubs from OpenAPI spec generated by backend:
https://github.com/zoubingwu/msw-auto-mock
`https://github.com/mswjs/msw/issues/394#issuecomment-840149992`

---

https://github.com/testing-library/jest-dom can be used as Assertions API even without Jest

--- 
Kotest for `BeforeAll`/`AfterAll` functionality and asserts api (supports only IR)

**Comment by akuleshov7** [comment]
Can be interesting for you Nariman: new technologies and to get familiar with KotlinJS

**Comment by petertrr** [comment]
As discussed, at first I'll try to create some foundation for this task
