### ISSUE TITLE
Create entity Owner

### ISSUE THREAD

**Issue by Cheshiriks** [analysis-dev/save-cloud#544]
- сreate entity Owner
- code refactor

**Comment by petertrr** [comment]
I thought it should be entity Organization? And owner will be simply a mapping to users?

**Comment by Cheshiriks** [comment]
I thought the owner was the organization. And the creator will be the user. But we can do as you suggest.

**Comment by Cheshiriks** [comment]
> I thought the owner was the organization. And the creator will be the user. But we can do as you suggest.

I thought the owner was the organization. And the creator will be the user. But we can do as you suggest.

**Comment by petertrr** [comment]
Yes, right, owner of a project is an organization. And creator of a project is a user. But I still think that calling organization as Organization will be less confusing than Owner.
