### ISSUE TITLE
Support the active top bar on the Project View

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/save-cloud#552]
The idea is mostly same to GitHub projects:
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/58667063/150646654-55cccc19-3b5f-4c9f-a9d9-8f99c74d75f6.png">

We should have: Run configuration, Setting, Statistics, Runs, Decription views inside

**Comment by Cheshiriks** [comment]
Was done in 607
