### ISSUE TITLE
Debug info is not avaliable from frontend

### ISSUE THREAD

**Issue by kgevorkyan** [analysis-dev/save-cloud#558]
```bash
13:19:11.557 [reactor-http-epoll-6] DEBUG o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler - [b713ff76-5] Resolved [ResponseStatusException: 404 NOT_FOUND "Test execution not found for executionId=7 and TestResultLocation(testSuiteName=Only Warnings: General, pluginName=WarnPlugin, testLocation=, testName=warn)"] for HTTP POST /api/testExecutions
```

Probably because of empty `testLocation`

**Comment by petertrr** [comment]
It appears we are using react-router incorrect: [docs](https://reactrouter.com/docs/en/v6/getting-started/overview#descendant-routes) mention trailing `*` only for nested routes. We'll need to inspect `params` object in `testExecutionDetailsView`

**Comment by petertrr** [comment]
Apparently, the rest of the URL is getting captured as `params["*"]`
