### ISSUE TITLE
CreateOrganization View 

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/save-cloud#562]
We need to create a logic for the creation of new organizations. What is needed from you:
![image](https://user-images.githubusercontent.com/58667063/152341924-b315a7c7-563d-40cb-9c6b-a6df07fd160a.png)

1) Create new Organization button; 
2) Create new View for the creation of the Organization;
3) Backend endpoint that will create organization ();  
4) Database update with a new organization;

Later, after Organization view will be ready - we will also we will also need a create new project from the organization view

**Comment by Cheshiriks** [comment]
You also need to create those organizations that we have are the owners of projects on the prod. And update the prod database for mapping the project to the organization.

**Comment by sanyavertolet** [comment]
When we merge #610, I will need to add uploading organization avatar when creating organization.

**Comment by akuleshov7** [comment]
> When we merge #610, I will need to add uploading organization avatar when creating organization.

not critical at all, backlog. Thank you for the initial contribution
