### ISSUE TITLE
Support setting user permissions from frontend

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/save-cloud#598]
* Organization admin should be able to add organization members with VIEWER or ADMIN roles
* The first organization admin is the user who created it

We need to
* [x] https://github.com/analysis-dev/save-cloud/issues/622
* [x] Support this API from frontend

**Comment by sanyavertolet** [comment]
Right now we have all the tasks done for projects permissions. (#621, #669, #686).
Soon the same things will be implemented for organizations (#708)

**Comment by sanyavertolet** [comment]
#708 is closed so permission management from frontend is implemented.
