### ISSUE TITLE
Create view for settings menu in projectView

### ISSUE THREAD

**Issue by Cheshiriks** [analysis-dev/save-cloud#621]
Need add:
- [x] users with role in project
- [x] check box for public/private project
- [x] move button _Delete project_ from Run menu
- [x] number of containers
- [x] email for project
- [x] check to permit/prohibit editing project settings according to user permissions

**Comment by petertrr** [comment]
On this tab we'll also have permission management described in #598

**Comment by sanyavertolet** [comment]
@akuleshov7 what do you mean by saying "number of containers"? Should it be a dropdown where you can choose amount of containers to be used for testing or it's just a label that indicates amount of containers dedicated for a project?

**Comment by petertrr** [comment]
@sanyavertolet Also, project settings shouldn't be editable if the user doesn't have permissions to edit them. Now we'll just display a 403 error, but there should be some other check too

**Comment by sanyavertolet** [comment]
Closed with #652 and #641
