### ISSUE TITLE
Organizations should be selected from the LIST of EXISTING organizations created by THIS user

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/save-cloud#623]
![image](https://user-images.githubusercontent.com/58667063/158956899-363adede-4713-44eb-9c3f-d6345f6e910f.png)

**Comment by petertrr** [comment]
@Cheshiriks do you handle the case, when user has zero organizations? Or will it be just a blank field? Could you please check and make fix it in an additional PR

**Comment by Cheshiriks** [comment]
If user has zero organizations when will it be just a blank field. Therefore, we moved the button here to create an organization.

**Comment by Cheshiriks** [comment]
> If user has zero organizations when will it be just a blank field. Therefore, we moved the button here to create an organization.

If user has zero organizations when will it be just a blank field. Therefore, we moved the button here to create an organization.

**Comment by Cheshiriks** [comment]
> @Cheshiriks do you handle the case, when user has zero organizations? Or will it be just a blank field? Could you please check and make fix it in an additional PR

If user has zero organizations when will it be just a blank field. Therefore, we moved the button here to create an organization.

**Comment by petertrr** [comment]
I see. We could still have a placeholder in case select is empty, because for example I didn't notice the button :)
