### ISSUE TITLE
Authorization: improvements

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/save-cloud#626]
1) when something goes wrong with authorization providers (Github/Codehub) - user should not see a blank page with an error (it should be handled in a proper way)

2) if user does not has a permission (for example - not authorised to see some project or even was not logged in) we should not silently redirect him to the login page. For user it looks like a bug.

**Comment by petertrr** [comment]
> 2. if user does not has a permission (for example - not authorised to see some project or even was not logged in) we should not silently redirect him to the login page. For user it looks like a bug.

Actually, after #602 it should be relatively easily fixable. I've kept the former logic for 401 codes (with redirect), but we can replace it with displaying custom error popup with login prompt (which will then redirect to main page, or just perform login right there)

If the user doesn't have permissions, we should already see the 403 error popup, I've only kept logic with redirects for 401, when the user is not logged it at all.

**Comment by petertrr** [comment]
> 1. when something goes wrong with authorization providers (Github/Codehub) - user should not see a blank page with an error (it should be handled in a proper way)

Related: #409. We could make a dedicated page for unsuccessful logins, but a generic one will be useful as well.
