### ISSUE TITLE
The logic for the deleting of projects is not working 

### ISSUE THREAD

**Issue by akuleshov7** [analysis-dev/save-cloud#755]
Before:
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/58667063/168431760-1f29a78c-b193-4749-9825-f1c83445df6b.png">

After (nothing changed):
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/58667063/168431823-0c8a6782-135a-40c9-b9cf-ed69bc463f38.png">

**Comment by petertrr** [comment]
The root cause is a redundant `window.reload()` right after the API request. Coroutine was forced to cancel and we didn't see any indication of an error
